name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - audioread=3.0.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - contourpy=1.0.7
  - cycler=0.11.0
  - decorator=5.1.1
  - filelock=3.12.0
  - fonttools=4.39.4
  - idna=3.4
  - importlib-resources=5.12.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - lazy-loader=0.2
  - librosa=0.10.0
  - llvmlite=0.40.0
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - mpmath=1.3.0
  - msgpack=1.0.5
  - networkx=3.1
  - numba=0.57.0
  - numpy=1.24.3
  - packaging=23.1
  - pandas=2.0.1
  - pillow=9.5.0
  - platformdirs=3.5.1
  - pooch=1.7.0
  - pycparser=2.21
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pytz=2023.3
  - requests=2.31.0
  - resampy=0.4.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - six=1.16.0
  - soundfile=0.12.1
  - soxr=0.3.5
  - sympy=1.12
  - threadpoolctl=3.1.0
  - torch=2.0.1
  - torchvision=0.15.2
  - tqdm=4.65.0
  - typing-extensions=4.6.2
  - tzdata=2023.3
  - urllib3=2.0.2
  - xgboost=1.7.5
  - zipp=3.15.0
